// Generated by msggen from D:\dev\eclipse\workspace\Caesar\cc/CaesarMessages.msg
package org.caesarj.compiler;

import org.caesarj.util.MessageDescription;

public interface CaesarMessages extends org.caesarj.util.Messages {
  MessageDescription	NO_PACKAGE_VISIBILITY = new MessageDescription("cclass field or method \"{0}\" must have private, protected or public visibility", "CLS TBD", 0);
  MessageDescription	CLEAN_ABSTRACT_CLASS = new MessageDescription("a cclass may not be declared abstract", "CLS TBD", 0);
  MessageDescription	CLEAN_CLASS_THISCALL = new MessageDescription("cclass constructors may not issue this constructor calls", "FJLS 1.9", 0);
  MessageDescription	WEAVING_STARTED = new MessageDescription("[ weaving started ]", null, 4);
  MessageDescription	WEAVING_ENDED = new MessageDescription("[ weaving ended ]", null, 4);
  MessageDescription	WROTE_CLASS_FILE = new MessageDescription("[ wrote class file: {0} ]", null, 4);
  MessageDescription	WEAVING_FAILED = new MessageDescription("weaving failed", null, 0);
  MessageDescription	PROCEED_OUTSIDE_AROUND_ADVICE = new MessageDescription("proceed() can only be used inside an around-advice", null, 0);
  MessageDescription	ADVICE_FLAGS = new MessageDescription("only strictfp modifier allowed for Advices", null, 0);
  MessageDescription	WEAVER_ERROR = new MessageDescription("{0}", null, 0);
  MessageDescription	ASPECTJ_ERROR = new MessageDescription("{0}", null, 0);
  MessageDescription	ASPECTJ_WARNING = new MessageDescription("{0}", null, 2);
  MessageDescription	POINTCUTS_OR_ADVICES_IN_NON_CCLASS = new MessageDescription("pointcuts and advices may not be declared in an ordinary class but only in a cclass", null, 0);
  MessageDescription	DEPLOYED_CLASS_CONSTRUCTOR_NON_PRIVATE_OR_WITH_PARAMETER = new MessageDescription("the constructor of a statically deployed class must be private and must not have any parameters", null, 0);
  MessageDescription	DEPLOYED_FIELD_NOT_FINAL_AND_STATIC = new MessageDescription("statically deployed fields must be declared final and static", null, 0);
  MessageDescription	DESCENDANT_OF_CCLASS_NOT_DECLARED_CCLASS = new MessageDescription("descendants of cclass must be cclass", null, 0);
  MessageDescription	WRAPPER_DEFINES_CONSTRUCTOR = new MessageDescription("Explicity declared wrapper class \"{0}\" cannot define constructors with parameters.", null, 0);
  MessageDescription	NON_BINDING_WRAPPER = new MessageDescription("Class \"{0}\" cannot define \"wraps\" clause because it does not bind a collaboration interface.", null, 0);
  MessageDescription	WRAPPER_DESTRUCTOR_NOT_FOUND = new MessageDescription("Cannot find wrapper \"{0}\" with matching parameters.", null, 0);
}
