package org.caesarj.compiler;

import org.caesarj.kjc.CClassNameType;
import org.caesarj.kjc.CReferenceType;

/**
 * @author Walter Augusto Werner
 */
public class CciConstants
	extends FjConstants
{
	public static final String ORDINARY_PARAMETER_PREFIX = 
		(SEPERATOR + "param").intern();
	public static final int DEFAULT_NUMERIC_RETURN = 0;
	public static final boolean DEFAULT_BOOLEAN_RETURN = false;
	public static final String PROVIDING_NAME = 
		(SEPERATOR + "providing").intern();
	public static final String PROVIDING_REFERENCE_NAME = 
		(PROVIDING_NAME + "Reference").intern();	 
	public static final String BINDING_NAME = 
		(SEPERATOR + "binding").intern();
	public static final String ACCESSOR_PREFIX =
		(SEPERATOR + "get").intern(); 
	public static final String SETTING_PREFIX = 
		(SEPERATOR + "set").intern(); 

	public static final String DEFAULT_CAESAR_JAVADOC_TEXT = 
		"Automatically Generated by Caesar: ";

	protected static final String WRAPPING_CREATION_PREFIX = 
		(SEPERATOR + "createWrapper").intern(); 
	public static final String WRAPPING_LOCAL_VAR = 
		(SEPERATOR + "localWrapper").intern(); 
	public static final String WRAPPING_MAP_ACCESS = 
		("get").intern(); 
	public static final String WRAPPING_MAP_PUT = 
		("put").intern(); 
		
	public static final String WRAPPEE_ID_METHOD_NAME = 
		(SEPERATOR + "getObjectId").intern();
	public static final String WRAPPEE_PARAMETER_NAME = 
		(SEPERATOR + "internalWrappee").intern(); 		
		
	public static final CReferenceType WRAPPING_MAP_TYPE = 
		new CClassNameType("java/util/WeakHashMap".intern());
	public static final JavadocComment WRAPPING_MAP_JAVADOC = 
		new JavadocComment(
			toCaesarJavadocText("Wrapping recycling map."), true, false);
	public static final JavadocComment WRAPPING_CREATION_JAVADOC = 
		new JavadocComment(
			toCaesarJavadocText("Wrapping recycling accessor/factory."), true, false);

	
	private static String fixName(String name)
	{
		if (name.startsWith("_"))
			name = name.substring(1);
		return name.substring(0, 1).toUpperCase() + name.substring(1);
	}
	
	public static String toCaesarJavadocText(String text)
	{
		return DEFAULT_CAESAR_JAVADOC_TEXT + text;
	}
	
	public static String toWrappingMapName(String bindingType)
	{
		return (bindingType.substring(0, 1).toLowerCase() 
			+ bindingType.substring(1)).intern();
	}

	public static String toWrappingMethodCreationName(String bindingType)
	{
		return (WRAPPING_CREATION_PREFIX + bindingType).intern();
	}
	
	public static String toAccessorMethodName(String name)
	{
		return ACCESSOR_PREFIX + fixName(name);
	}
	public static String toSettingMethodName(String name)
	{
		return SETTING_PREFIX + fixName(name);
	}
	
	public static boolean isSettingMethodName(String name)
	{
		return toSettingMethodName(PROVIDING_NAME).equals(name)
				|| toSettingMethodName(BINDING_NAME).equals(name);
	}
}
