// Generated by msggen from OptimizeMessages.msg
package org.caesarj.compiler.optimize;

import org.caesarj.util.MessageDescription;

public interface OptimizeMessages extends org.caesarj.util.Messages {
  MessageDescription	SEMANTIC_ERROR = new MessageDescription("Semantic error found on file \"{0}\": {1}", "OPTIMIZE", 0);
}
