/*
 * This source file is part of CaesarJ 
 * For the latest info, see http://caesarj.org/
 * 
 * Copyright © 2003-2005 
 * Darmstadt University of Technology, Software Technology Group
 * Also see acknowledgements in readme.txt
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 * 
 * $Id: CaesarByteCodeNavigator.java,v 1.5 2005-01-24 16:53:03 aracic Exp $
 */

package org.caesarj.navigator;

import java.io.IOException;

import org.caesarj.compiler.ClassReader;
import org.caesarj.compiler.KjcClassReader;
import org.caesarj.compiler.export.CClass;
import org.caesarj.compiler.types.KjcSignatureParser;
import org.caesarj.compiler.types.KjcTypeFactory;
import org.caesarj.compiler.types.TypeFactory;

/**
 * This class is used for reconstructing the type information from bytecode
 * generated by the Caesar compiler.
 * It uses KjcClassReader and KjcTypeFactory as backend.
 * 
 * @author Ivica Aracic
 */
public class CaesarByteCodeNavigator {

    private ClassReader classReader;
    private TypeFactory factory;
        
    /**
     * @param extDirs extra directories that should be appended to the classpath
     */
    public CaesarByteCodeNavigator(String extDirs) {
        classReader = new KjcClassReader(null, extDirs, new KjcSignatureParser());
        factory = new KjcTypeFactory(classReader);
    }
    
    /**
     * generates the export informations of a class from the classpath
     */
    public CClass load(String qn) {        
        return classReader.loadClass(factory, qn);
    }
    
    /**
     * This method demonstrates the usage of CaesarByteCodeNavigator
     */
    public static void main(String[] args) throws IOException {
        CaesarByteCodeNavigator nav = new CaesarByteCodeNavigator("tests/VirtualClassesTests");
        
        CClass clazz = nav.load("generated/test3/TestCase3$CWG");
        
        System.out.println(clazz.getAdditionalTypeInformation());
    }
}
