// Generated by msggen from AntlrMessages.msg
package org.caesarj.compiler.tools.antlr.compiler;

import org.caesarj.util.MessageDescription;

public interface AntlrMessages extends org.caesarj.compiler.CompilerMessages {
}
