// Generated by msggen from LexgenMessages.msg
package org.caesarj.compiler.tools.lexgen;

import org.caesarj.util.MessageDescription;

public interface LexgenMessages extends org.caesarj.compiler.CompilerMessages {
  MessageDescription	DUPLICATE_DEFINITION = new MessageDescription("Token \"{0}\" redefined in \"{1}\": previous definition in \"{2}\"", "LEXGEN", 0);
}
