// Generated by msggen from ClassfileMessages.msg
package org.caesarj.classfile;

import org.caesarj.util.MessageDescription;

public interface ClassfileMessages extends org.caesarj.compiler.CompilerMessages {
}
