// Generated by msggen from LexgenMessages.msg
package org.caesarj.tools.lexgen;

import org.caesarj.util.MessageDescription;
import org.caesarj.util.Messages;

public interface LexgenMessages extends Messages {
  MessageDescription	DUPLICATE_DEFINITION = new MessageDescription("Token \"{0}\" redefined in \"{1}\": previous definition in \"{2}\"", "LEXGEN", 0);
}
