#!/bin/sh

if [ "$CAESAR_HOME" = "" ]; then 
	echo "please set CAESAR_HOME environment variable"
	exit
fi

export CAESAR_LIBS="$CAESAR_HOME/dist/caesar-compiler.jar:$CAESAR_HOME/lib/aspectjtools.jar"

java -classpath $CAESAR_LIBS org.caesarj.compiler.Main $*
