// Generated by optgen from ServerOptions.opt
package org.caesarj.ikjc;

import gnu.getopt.Getopt;
import gnu.getopt.LongOpt;

public class ServerOptions extends org.caesarj.util.Options {

  public ServerOptions(String name) {
    super(name);
  }

  public ServerOptions() {
    this("Server");
  }
  public int port = 4444;
  public boolean verbose = false;

  public boolean processOption(int code, Getopt g) {
    switch (code) {
    case 'p':
      port = getInt(g, 0); return true;
    case 'v':
      verbose = !false; return true;
    default:
      return super.processOption(code, g);
    }
  }

  public String[] getOptions() {
    String[]	parent = super.getOptions();
    String[]	total = new String[parent.length + 2];
    System.arraycopy(parent, 0, total, 0, parent.length);
    total[parent.length + 0] = "  --port, -p<int>:      the port number for incoming connections [4444]";
    total[parent.length + 1] = "  --verbose, -v:        Prints out information about connections [false]";
    
    return total;
  }


  public String getShortOptions() {
    return "p:v" + super.getShortOptions();
  }


  public void version() {
    System.out.println("Version 2.1A released 11. February 2002");
  }


  public void usage() {
    System.err.println("usage: org.caesarj.ikjc.Server [option]* <files>");
  }


  public void help() {
    System.err.println("usage: org.caesarj.ikjc.Server [option]* <files>");
    printOptions();
    System.err.println();
    version();
    System.err.println();
    System.err.println("This program is part of the Kopi Suite.");
    System.err.println("For more info, please see: http://www.dms.at/kopi");
  }

  public LongOpt[] getLongOptions() {
    LongOpt[]	parent = super.getLongOptions();
    LongOpt[]	total = new LongOpt[parent.length + LONGOPTS.length];
    
    System.arraycopy(parent, 0, total, 0, parent.length);
    System.arraycopy(LONGOPTS, 0, total, parent.length, LONGOPTS.length);
    
    return total;
  }

  private static final LongOpt[] LONGOPTS = {
    new LongOpt("port", LongOpt.REQUIRED_ARGUMENT, null, 'p'),
    new LongOpt("verbose", LongOpt.NO_ARGUMENT, null, 'v')
  };
}
