// Generated by msggen from IncludeMessages.msg
package org.caesarj.tools.include;

import org.caesarj.util.MessageDescription;

public interface IncludeMessages extends org.caesarj.util.Messages {
  MessageDescription	CANNOT_OPEN_FILE = new MessageDescription("Cannot open file \"{0}\": {1}", "INCLUDE", 0);
}
